### PR TITLE
Fix overflow for long value

### PR DESCRIPTION
**Pull request by MyCADDev**
Hi,
Could you review this change which fixes an overflow issue in Long values (both iOS and Android).

thanks

### CODE REVIEW

**Comment by vals-productions** [comment]
Hi MyCADDev, 

Nice catch, and thank you for the contribution!

I have several questions for you:

1) You've modified SqliteDb.SqliteRs.getObject(...) for Andtoid, but I do not see similar change for iOS in SqlighterRsImpl.m getObjectWithInt

2) Similarly, there's modification to SqlighterDbImpl.m for bindParameters(...) for iOS, but no mod for Android. 

Which part were you going to change? 

The change you've proposed is important, so, lets sort it out.

Vlad.

**Comment by vals-productions** [comment]
Oops, sorry, my second (2) note is invalid, disregard it please as Android code for bind parameter is correct and the fix was only needed for iOS. Your change to bindParameters is correct.

Regarding (1), the concern is that if some table column contains wide range of values then getObject(... ) might return Integer or Long classes depending on row's value, and this will lead to class cast exceptions unless the user is specifically accounting for this scenario.

Would it work for your situation if it was implemented this way:

The flag is introduced to SqlighterDB class, let's say:
Const int DEFAULT_INTEGER_COLUMN_CLASS_INTEGER = 0;
Const int DEFAULT_INTEGER_COLUMN_CLASS_LONG = 1;
int defaultIntegerColumnClass = DEFAULT_INTEGER_COLUMN_CLASS_INTEGER;

getObject(...) would return Integer or Long based on the flag.

By default it would be an Integer (for backward compatibility), but you can set it to always return Long values and that should satisfy your case.

If it's important for you to have the mix of Integers and Longs to be returned, then, there could be another constant DEFAULT_INTEGER_COLUMN_CLASS_MIXED =3; that engages your algorithm.

Let me know.

Vlad.

**Comment by MyCADDev** [comment]
I agree with your comments. I also encountered the class cast exception in the situation where the long field had small values and integer was sufficient.

Yes I'd like the DEFAULT_INTEGER_COLUMN_CLASS_MIXED.

Let me know if you need help with writing unit tests.

I also have a local gradle build which can build the JAR and iOS static library. Its far from perfect but I can help in this area too (if you plan for a traditional gradle build test system for this project).

**Comment by vals-productions** [comment]
Ok, great, would you like to make changes to the pull request to reflect our discussion?

**Comment by vals-productions** [comment]
Speaking of tests, right now they are incorporated in the Demo project that is j2objc'd into objective C and, therefore, tests are available for both platforms. It, probably needs to be refactored so that each test is in its own method.

**Comment by MyCADDev** [comment]
I will need some guidance on how this should be done.
Ideally the class bound to the ORM should be used to determine what the type to which the SqLite INTEGER should be deserialized to. 

Should this check be done only if DEFAULT_INTEGER_COLUMN_CLASS_MIXED is set?

What are your thoughts?

**Comment by vals-productions** [comment]
Do you refer to implementation or unit tests?

**Comment by MyCADDev** [comment]
I meant implementation

**Comment by vals-productions** [comment]
For now could you limit implementation to Sqlighter? With Integer as default it should work at least. There is some ORM update with new features coming soon, and I will make sure it works with your contribution.

**Pull request merged**
